name: Deploy website

on: workflow_dispatch

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        run: npm run deploy
